### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by adrianmiu** [AnyChart/graphicsjs#1]
http://docs.anychart.com/7.11.1/Graphics/Paths

> Sample parsing error!
> {sample}GFX_Paths_1{sample}

**Comment by RomanLubushkin** [comment]
Issue with two samples have fixed.
Thank you for your report!
![image](https://cloud.githubusercontent.com/assets/680750/18585803/a38d7dd8-7c4b-11e6-97c0-6c395a1458c4.png)
