### ISSUE TITLE
Diagram Flow  (Mxgrpah)

### ISSUE THREAD

**Issue by Diaskhan** [AnyChart/GraphicsJS#10]
1.Its possible to make Diagrams like Mxgraph doing ?
2.Possible to drag n drop support ?
3.Resizing and Manipulationg Gprahs ?

**Comment by Shestac92** [comment]
@Diaskhan 
Please, can you provide a sample or screenshot of the required diagram type?

The AnyChart charts are based on JS code (JSON and XML configs are available). Drag'n'drop is available for some interactive chart elements. Resizing and manipulations are also available for many interactive elements, like scroller, annotations, datagrids and so on.
You can learn more about creating a chart in [the quick start article](https://docs.anychart.com/Quick_Start/Quick_Start).

**Comment by Diaskhan** [comment]
![image](https://user-images.githubusercontent.com/15046677/56034724-f66f5d00-5d49-11e9-9f30-e6e5ecce35d5.png)

**Comment by Shestac92** [comment]
@Diaskhan 
Unfortunately, the library doesn't provide such a flow diagram. All available chart-types you can find at [this page](https://www.anychart.com/features/#chart-types).
