### ISSUE TITLE
README.md's QuickStart script src incorrect

### ISSUE THREAD

**Issue by lenkite** [AnyChart/GraphicsJS#7]
It mentions https://cdn.anychart.com/releases/js/v8/graphics.min.js which gives 500 internal server error.

**Comment by Shestac92** [comment]
@lenkite 
Thank you for your report! I guess that the link in the example was not updated in time. You may download the latest version of the required module from our CDN. The direct link on the graphics.min.js - https://cdn.anychart.com/releases/8.1.0/js/graphics.min.js

**Comment by Shestac92** [comment]
The code example was fixed.
