### ISSUE TITLE
Nodejs: Cannot find module 'graphicsjs'

### ISSUE THREAD

**Issue by A134025** [AnyChart/GraphicsJS#9]
After successful installation package with npm, i write to server.js
var G=require('graphicsjs') 
and at startup receive Error: Cannot find module 'graphicsjs'
Package version: 1.3.2

**Comment by Shestac92** [comment]
@A134025 
Unfortunately, the current version of GraphicsJS is not available for using with NodeJS as it's a browser specific module and it requires a window object and many other browser specific features.
